# Generated by Django 2.2.5 on 2020-02-15 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('ingredient', models.TextField(default='[]')),
                ('cost', models.FloatField()),
                ('additional_meals', models.TextField(default='[]]')),
                ('additional_drinks', models.TextField(default='[]]')),
                ('additional_deserts', models.TextField(default='[]]')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('comment', models.TextField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meals.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
