# Generated by Django 2.2.5 on 2020-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0002_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='additional_deserts',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='additional_drinks',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='additional_meals',
            field=models.TextField(default='[]'),
        ),
    ]
