# Generated by Django 2.2.5 on 2020-02-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0003_auto_20200215_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
