# Generated by Django 2.2.5 on 2019-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.BinaryField()),
                ('ingredient', models.TextField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
