# Generated by Django 2.2.5 on 2020-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
