# Generated by Django 2.2.5 on 2020-02-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orders',
            new_name='deserts',
        ),
        migrations.AddField(
            model_name='order',
            name='drinks',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
