# Generated by Django 2.2.5 on 2020-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20200216_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='999', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
